name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ngocvd4/ep-platform:latest

    - name: Force new ECS deployment
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ./ecs-fargate/task-definition.json
        service: ep-platform-service
        cluster: ep-platform-cluster
        wait-for-service-stability: true
        region: ap-northeast-1
